name: Fly Deploy

# Trigger this workflow only after the 'Check Code' workflow completes successfully
on:
  workflow_run:
    workflows: ["Rust Script CI"]   # replace with the exact name of your check workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only deploy if checks passed
    name: Deploy website to Fly
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensures only one deploy at a time
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}